/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xdrxml_t_xml.h"

bool_t
xdr_strul (xdrs, objp)
	XDR *xdrs;
	strul *objp;
{
	XDR_LABEL label;
	register int32_t *buf;

	xdr_label_push(xdrs, &label, "strul", "string");
	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	xdr_label_pop(xdrs);
	return TRUE;
}

bool_t
xdr_rec_person (xdrs, objp)
	XDR *xdrs;
	rec_person *objp;
{
	XDR_LABEL label;
	register int32_t *buf;

	xdr_label_push(xdrs, &label, "name", "strul");
	 if (!xdr_strul (xdrs, &objp->name))
		 return FALSE;
	xdr_label_pop(xdrs);
	xdr_label_push(xdrs, &label, "age", "int");
	 if (!xdr_int (xdrs, &objp->age))
		 return FALSE;
	xdr_label_pop(xdrs);
	xdr_label_push(xdrs, &label, "wieght", "float");
	 if (!xdr_float (xdrs, &objp->wieght))
		 return FALSE;
	xdr_label_pop(xdrs);
	return TRUE;
}

bool_t
xdr_rec_classroom (xdrs, objp)
	XDR *xdrs;
	rec_classroom *objp;
{
	XDR_LABEL label;
	register int32_t *buf;

	xdr_label_push(xdrs, &label, "title", "strul");
	 if (!xdr_strul (xdrs, &objp->title))
		 return FALSE;
	xdr_label_pop(xdrs);
	xdr_label_push(xdrs, &label, "students", "rec_person");
	 if (!xdr_array (xdrs, (char **)&objp->students.students_val, (u_int *) &objp->students.students_len, ~0,
		sizeof (rec_person), (xdrproc_t) xdr_rec_person))
		 return FALSE;
	xdr_label_pop(xdrs);
	return TRUE;
}

bool_t
xdr_rec_type (xdrs, objp)
	XDR *xdrs;
	rec_type *objp;
{
	XDR_LABEL label;
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rec (xdrs, objp)
	XDR *xdrs;
	rec *objp;
{
	XDR_LABEL label;
	register int32_t *buf;

	xdr_label_push(xdrs, &label, "type", "rec_type");
	 if (!xdr_rec_type (xdrs, &objp->type))
		 return FALSE;
	xdr_label_pop(xdrs);
	switch (objp->type) {
	case REC_PERSON:
		xdr_label_push(xdrs, &label, "person", "rec_person");
		 if (!xdr_rec_person (xdrs, &objp->rec_u.person))
			 return FALSE;
		xdr_label_pop(xdrs);
		break;
	case REC_CLASSROOM:
		xdr_label_push(xdrs, &label, "classroom", "rec_classroom");
		 if (!xdr_rec_classroom (xdrs, &objp->rec_u.classroom))
			 return FALSE;
		xdr_label_pop(xdrs);
		break;
	}
	return TRUE;
}
